Algoritmo "Celsius para Fahrenheit"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Barros
// Autor(a)    : Alan Mateus
// Data atual  : 20/09/2021
Var
   celsius, fahrenheit: Real
Inicio
      // Entrada
      escreval("Informe o valor em graus Celsius")
      leia(celsius)

      // Processamento
      fahrenheit <- ((9/5) * celsius) + 32

      // Saída
      escreval("A temperatura de ", celsius, " graus Celsius equivale a", fahrenheit, " graus Fahrenheit")

Fimalgoritmo