Algoritmo "Celsius para Fahrenheit"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Barros
// Autor(a)    : Alan Mateus
// Data atual  : 27/09/2021
Var
   celsius, fahrenheit: real
Inicio
      escreval("Informe a temperatura em Celsius")
      leia(celsius)
      
      fahrenheit <- ((9/5) * celsius) + 32
      
      escreval("A temperatura em Fahrenheit é: ", fahrenheit)
Fimalgoritmo