Algoritmo "Exercicio 14"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Barros
// Autor(a)    : Alan Mateus
// Data atual  : 02/09/2021
Var
   numero, quociente: Inteiro
Inicio
      // Entrada
      escreval("Informe o número, por favor")
      leia(numero)
      
      // Processamento
      quociente <- (numero div 3)
      
      // Saída
      escreval("O quociente da divisão por 3 é: ", quociente)
      
Fimalgoritmo