Algoritmo "Exercicio 18"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Barros
// Autor(a)    : Alan Mateus
// Data atual  : 02/09/2021
Var
   nome,endereco: Caractere
   idade: Inteiro
Inicio
      // Entrada
      escreval("Informe o seu nome, idade e endereço, em sequencia, por favor")
      leia(nome, idade, endereco)
      
      escreval("Nome: ", nome)
      escreval("Idade: ", idade)
      escreval("Endereço: ", endereco)
      
Fimalgoritmo