Algoritmo "Exercicio 15"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Barros
// Autor(a)    : Alan Mateus
// Data atual  : 02/09/2021
Var
   numero, resto: Inteiro
Inicio
      // Entrada
      escreval("Informe o número, por favor")
      leia(numero)
      
      // Processamento
      resto <- (numero % 3)
      
      // Saída
      escreval("O resto da divisão por 3 é: ", resto)
      
Fimalgoritmo